[tool.pyright]
include = [
  "app",
]
exclude = [
  "app/prisma",
  "app/tests",
]

typeCheckingMode = "strict"

[tool.mypy]
follow_imports = "normal"
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_untyped_calls = true
install_types = true
non_interactive = true

[[tool.mypy.overrides]]
module = "app.tests.*"
ignore_errors = true

[tool.black]
line-length = 100
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | app/prisma
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
skip_glob = ["app/prisma/*"]

[tool.pytest.ini_options]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
testpaths = ["app"]
addopts = "-v -rsxX -l --tb=short --strict --cov=app -p no:warnings"
xfails_strict = true
markers = [
  "tmp: Temporary",
  "optional: Optional"
]
env = [
  "APP_CONFIG_FILE=test"
]
flake8-max-line-length = 100
flake8-max-complexity = 30
flake8-ignore = [
  "*.py",
  "tests/*.py ALL",
]
asyncio_mode = "auto"
