# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Callable,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
import os
import logging
import inspect
import warnings
from pydantic import BaseConfig, BaseModel, Field, validator

from . import types, enums, errors, fields
from ._types import BaseModelT, FuncType
from .builder import serialize_base64
from .generator import partial_models_ctx, PartialModelField


class Config(BaseConfig):
    use_enum_values: bool = True
    arbitrary_types_allowed: bool = True
    allow_population_by_field_name: bool = True
    json_encoders: Dict[Any, FuncType] = {
        fields.Base64: serialize_base64,
    }


log: logging.Logger = logging.getLogger(__name__)
_created_partial_types: Set[str] = set()

# packages that implicitly subclass models
# this should not raise any warnings as users
# of these packages cannot do anything about it
_implicit_subclass_packages: Set[str] = {
    'fastapi',
}


def _maybe_warn_subclassing(new_model: str, base_model: str, *, stacklevel: int = 3) -> None:
    # at least 3 frames are guaranteed to exist if we are being called from __init_subclass__
    # stack: 1 = __init_subclass__, 2 = abc, 3 = <caller>
    try:
        frame = inspect.stack()[stacklevel]
        module = inspect.getmodule(frame[0])
        if module is not None:
            name, *_ = module.__name__.split('.')
            if name in _implicit_subclass_packages:
                return
    except Exception as exc:
        # disabling subclass warnings depending on the caller module is not a mission critical
        # feature, users can disable these warnings themselves
        # https://github.com/RobertCraigie/prisma-client-py/issues/278#issuecomment-1031421561
        log.debug('Ignoring exception encountered during stack inspection check: %s', str(exc))

    message = (
        'Subclassing models while using pseudo-recursive types may cause unexpected '
        'errors when static type checking;\n'
        'You can disable this warning by generating fully recursive types: \n'
        'https://prisma-client-py.readthedocs.io/en/stable/reference/config/#recursive\n'
        'or if that is not possible you can pass warn_subclass=False e.g.\n'
        f'  class {new_model}(prisma.models.{base_model}, warn_subclass=False):'
    )
    warnings.warn(message, errors.UnsupportedSubclassWarning, stacklevel=4)


class Note(BaseModel):
    """Represents a Note record"""

    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: _int
    title: _str
    content: _str
    notebook_id: _int
    notebook: Optional['models.Notebook']

    Config = Config

    @classmethod
    def prisma(cls) -> 'actions.NoteActions':
        from .client import get_client

        return actions.NoteActions(get_client(), cls)

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: bool = True,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass:
            _maybe_warn_subclassing(cls.__name__, 'Note', stacklevel=3)

    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.NoteKeys']] = None,
        exclude: Optional[Iterable['types.NoteKeys']] = None,
        required: Optional[Iterable['types.NoteKeys']] = None,
        optional: Optional[Iterable['types.NoteKeys']] = None,
        relations: Optional[Mapping['types.NoteRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.NoteKeys', PartialModelField] = {}

        try:
            if include:
                for field in include:
                    fields[field] = _Note_fields[field]
            elif exclude:
                for field in exclude:
                    if field not in _Note_fields:
                        raise KeyError(field)

                fields = {
                    key: data
                    for key, data in _Note_fields.items()
                    if key not in exclude
                }
            else:
                fields = _Note_fields.copy()

            if required:
                for field in required:
                    fields[field] = fields[field].copy()
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field] = fields[field].copy()
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _Note_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _Note_relational_fields:
                        raise errors.UnknownRelationalFieldError('Note', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid Note / {name} field.'
            ) from None

        models = partial_models_ctx.get()

        # mypy does not like this as we are assigning a
        # Dict[Literal[str]] to a Dict[str] but this is fine
        models[name] = fields  # type: ignore[assignment]
        partial_models_ctx.set(models)
        _created_partial_types.add(name)


class Notebook(BaseModel):
    """Represents a Notebook record"""

    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: _int
    title: _str
    notes: Optional[List['models.Note']]

    Config = Config

    @classmethod
    def prisma(cls) -> 'actions.NotebookActions':
        from .client import get_client

        return actions.NotebookActions(get_client(), cls)

    # take *args and **kwargs so that other metaclasses can define arguments
    def __init_subclass__(
        cls,
        *args: Any,
        warn_subclass: bool = True,
        **kwargs: Any,
    ) -> None:
        super().__init_subclass__()
        if warn_subclass:
            _maybe_warn_subclassing(cls.__name__, 'Notebook', stacklevel=3)

    @staticmethod
    def create_partial(
        name: str,
        include: Optional[Iterable['types.NotebookKeys']] = None,
        exclude: Optional[Iterable['types.NotebookKeys']] = None,
        required: Optional[Iterable['types.NotebookKeys']] = None,
        optional: Optional[Iterable['types.NotebookKeys']] = None,
        relations: Optional[Mapping['types.NotebookRelationalFieldKeys', str]] = None,
        exclude_relational_fields: bool = False,
    ) -> None:
        if not os.environ.get('PRISMA_GENERATOR_INVOCATION'):
            raise RuntimeError(
                'Attempted to create a partial type outside of client generation.'
            )

        if name in _created_partial_types:
            raise ValueError(f'Partial type "{name}" has already been created.')

        if include is not None:
            if exclude is not None:
                raise TypeError('Exclude and include are mutually exclusive.')
            if exclude_relational_fields is True:
                raise TypeError('Include and exclude_relational_fields=True are mutually exclusive.')

        if required and optional:
            shared = set(required) & set(optional)
            if shared:
                raise ValueError(f'Cannot make the same field(s) required and optional {shared}')

        if exclude_relational_fields and relations:
            raise ValueError(
                'exclude_relational_fields and relations are mutually exclusive'
            )

        fields: Dict['types.NotebookKeys', PartialModelField] = {}

        try:
            if include:
                for field in include:
                    fields[field] = _Notebook_fields[field]
            elif exclude:
                for field in exclude:
                    if field not in _Notebook_fields:
                        raise KeyError(field)

                fields = {
                    key: data
                    for key, data in _Notebook_fields.items()
                    if key not in exclude
                }
            else:
                fields = _Notebook_fields.copy()

            if required:
                for field in required:
                    fields[field] = fields[field].copy()
                    fields[field]['optional'] = False

            if optional:
                for field in optional:
                    fields[field] = fields[field].copy()
                    fields[field]['optional'] = True

            if exclude_relational_fields:
                fields = {
                    key: data
                    for key, data in fields.items()
                    if key not in _Notebook_relational_fields
                }

            if relations:
                for field, type_ in relations.items():
                    if field not in _Notebook_relational_fields:
                        raise errors.UnknownRelationalFieldError('Notebook', field)

                    # TODO: this method of validating types is not ideal
                    # as it means we cannot two create partial types that
                    # reference each other
                    if type_ not in _created_partial_types:
                        raise ValueError(
                            f'Unknown partial type: "{type_}". '
                            f'Did you remember to generate the {type_} type before this one?'
                        )

                    # TODO: support non prisma.partials models
                    info = fields[field]
                    if info['is_list']:
                        info['type'] = f'List[\'partials.{type_}\']'
                    else:
                        info['type'] = f'\'partials.{type_}\''
        except KeyError as exc:
            raise ValueError(
                f'{exc.args[0]} is not a valid Notebook / {name} field.'
            ) from None

        models = partial_models_ctx.get()

        # mypy does not like this as we are assigning a
        # Dict[Literal[str]] to a Dict[str] but this is fine
        models[name] = fields  # type: ignore[assignment]
        partial_models_ctx.set(models)
        _created_partial_types.add(name)



_Note_relational_fields: Set[str] = {
        'notebook',
    }
_Note_fields: Dict['types.NoteKeys', PartialModelField] = {
    'created_at': {
        'name': 'created_at',
        'is_list': False,
        'optional': False,
        'type': 'datetime.datetime',
        'documentation': None,
    },
    'updated_at': {
        'name': 'updated_at',
        'is_list': False,
        'optional': False,
        'type': 'datetime.datetime',
        'documentation': None,
    },
    'id': {
        'name': 'id',
        'is_list': False,
        'optional': False,
        'type': '_int',
        'documentation': None,
    },
    'title': {
        'name': 'title',
        'is_list': False,
        'optional': False,
        'type': '_str',
        'documentation': None,
    },
    'content': {
        'name': 'content',
        'is_list': False,
        'optional': False,
        'type': '_str',
        'documentation': None,
    },
    'notebook_id': {
        'name': 'notebook_id',
        'is_list': False,
        'optional': False,
        'type': '_int',
        'documentation': None,
    },
    'notebook': {
        'name': 'notebook',
        'is_list': False,
        'optional': True,
        'type': 'models.Notebook',
        'documentation': None,
    },
}

_Notebook_relational_fields: Set[str] = {
        'notes',
    }
_Notebook_fields: Dict['types.NotebookKeys', PartialModelField] = {
    'created_at': {
        'name': 'created_at',
        'is_list': False,
        'optional': False,
        'type': 'datetime.datetime',
        'documentation': None,
    },
    'updated_at': {
        'name': 'updated_at',
        'is_list': False,
        'optional': False,
        'type': 'datetime.datetime',
        'documentation': None,
    },
    'id': {
        'name': 'id',
        'is_list': False,
        'optional': False,
        'type': '_int',
        'documentation': None,
    },
    'title': {
        'name': 'title',
        'is_list': False,
        'optional': False,
        'type': '_str',
        'documentation': None,
    },
    'notes': {
        'name': 'notes',
        'is_list': True,
        'optional': True,
        'type': 'List[\'models.Note\']',
        'documentation': None,
    },
}



# we have to import ourselves as relation types are namespaced to models
# e.g. models.Post
from . import models, actions

# required to support relationships between models
Note.update_forward_refs()
Notebook.update_forward_refs()
