# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template types.py.jinja --
from typing import TypeVar

import httpx
from .utils import _NoneType



# TODO: filters with aggregates should have their own recursive fields
# TODO: cleanup whitespace control
# TODO: add an argument to signify that the last iteration should be skipped


SortMode = Literal['default', 'insensitive']
SortOrder = Literal['asc', 'desc']

MetricsFormat = Literal['json', 'prometheus']


class _DatasourceOverrideOptional(TypedDict, total=False):
    env: str
    name: str


class DatasourceOverride(_DatasourceOverrideOptional):
    url: str


# NOTE: we don't support some options as their type hints are not publicly exposed
# https://github.com/encode/httpx/discussions/1977
class HttpConfig(TypedDict, total=False):
    app: Callable[[Mapping[str, Any], Any], Any]
    http1: bool
    http2: bool
    limits: httpx.Limits
    timeout: Union[None, float, httpx.Timeout]
    trust_env: bool
    max_redirects: int


# types that can be serialized to json by our query builder
Serializable = Union[
    None,
    bool,
    float,
    int,
    str,
    datetime.datetime,
    List[Any],
    Dict[None, Any],
    Dict[bool, Any],
    Dict[float, Any],
    Dict[int, Any],
    Dict[str, Any],
]


    

StringFilter = TypedDict(
    'StringFilter',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive1'],
        'mode': SortMode,
    },
    total=False,
)


StringFilterRecursive1 = TypedDict(
    'StringFilterRecursive1',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive2'],
        'mode': SortMode,
    },
    total=False,
)


StringFilterRecursive2 = TypedDict(
    'StringFilterRecursive2',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive3'],
        'mode': SortMode,
    },
    total=False,
)


StringFilterRecursive3 = TypedDict(
    'StringFilterRecursive3',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive4'],
        'mode': SortMode,
    },
    total=False,
)


StringFilterRecursive4 = TypedDict(
    'StringFilterRecursive4',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
                'mode': SortMode,
    },
    total=False,
)


class StringWithAggregatesFilter(StringFilter, total=False):
    _max: 'StringFilter'
    _min: 'StringFilter'
    _sum: 'StringFilter'
    _avg: 'StringFilter'
    _count: 'IntFilter'


    

DateTimeFilter = TypedDict(
    'DateTimeFilter',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive1'],
    },
    total=False,
)


DateTimeFilterRecursive1 = TypedDict(
    'DateTimeFilterRecursive1',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive2'],
    },
    total=False,
)


DateTimeFilterRecursive2 = TypedDict(
    'DateTimeFilterRecursive2',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive3'],
    },
    total=False,
)


DateTimeFilterRecursive3 = TypedDict(
    'DateTimeFilterRecursive3',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive4'],
    },
    total=False,
)


DateTimeFilterRecursive4 = TypedDict(
    'DateTimeFilterRecursive4',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
            },
    total=False,
)


class DateTimeWithAggregatesFilter(DateTimeFilter, total=False):
    _max: 'DateTimeFilter'
    _min: 'DateTimeFilter'
    _sum: 'DateTimeFilter'
    _avg: 'DateTimeFilter'
    _count: 'IntFilter'


    

BooleanFilter = TypedDict(
    'BooleanFilter',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive1'],
    },
    total=False,
)


BooleanFilterRecursive1 = TypedDict(
    'BooleanFilterRecursive1',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive2'],
    },
    total=False,
)


BooleanFilterRecursive2 = TypedDict(
    'BooleanFilterRecursive2',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive3'],
    },
    total=False,
)


BooleanFilterRecursive3 = TypedDict(
    'BooleanFilterRecursive3',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive4'],
    },
    total=False,
)


BooleanFilterRecursive4 = TypedDict(
    'BooleanFilterRecursive4',
    {
        'equals': bool,
            },
    total=False,
)


class BooleanWithAggregatesFilter(BooleanFilter, total=False):
    _max: 'BooleanFilter'
    _min: 'BooleanFilter'
    _sum: 'BooleanFilter'
    _avg: 'BooleanFilter'
    _count: 'IntFilter'


    

IntFilter = TypedDict(
    'IntFilter',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive1'],
    },
    total=False,
)


IntFilterRecursive1 = TypedDict(
    'IntFilterRecursive1',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive2'],
    },
    total=False,
)


IntFilterRecursive2 = TypedDict(
    'IntFilterRecursive2',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive3'],
    },
    total=False,
)


IntFilterRecursive3 = TypedDict(
    'IntFilterRecursive3',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive4'],
    },
    total=False,
)


IntFilterRecursive4 = TypedDict(
    'IntFilterRecursive4',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
            },
    total=False,
)


class IntWithAggregatesFilter(IntFilter, total=False):
    _max: 'IntFilter'
    _min: 'IntFilter'
    _sum: 'IntFilter'
    _avg: 'IntFilter'
    _count: 'IntFilter'


BigIntFilter = IntFilter
BigIntWithAggregatesFilter = IntWithAggregatesFilter
    

FloatFilter = TypedDict(
    'FloatFilter',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive1'],
    },
    total=False,
)


FloatFilterRecursive1 = TypedDict(
    'FloatFilterRecursive1',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive2'],
    },
    total=False,
)


FloatFilterRecursive2 = TypedDict(
    'FloatFilterRecursive2',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive3'],
    },
    total=False,
)


FloatFilterRecursive3 = TypedDict(
    'FloatFilterRecursive3',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive4'],
    },
    total=False,
)


FloatFilterRecursive4 = TypedDict(
    'FloatFilterRecursive4',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
            },
    total=False,
)


class FloatWithAggregatesFilter(FloatFilter, total=False):
    _max: 'FloatFilter'
    _min: 'FloatFilter'
    _sum: 'FloatFilter'
    _avg: 'FloatFilter'
    _count: 'IntFilter'


    

BytesFilter = TypedDict(
    'BytesFilter',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive1'],
    },
    total=False,
)


BytesFilterRecursive1 = TypedDict(
    'BytesFilterRecursive1',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive2'],
    },
    total=False,
)


BytesFilterRecursive2 = TypedDict(
    'BytesFilterRecursive2',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive3'],
    },
    total=False,
)


BytesFilterRecursive3 = TypedDict(
    'BytesFilterRecursive3',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive4'],
    },
    total=False,
)


BytesFilterRecursive4 = TypedDict(
    'BytesFilterRecursive4',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
            },
    total=False,
)


class BytesWithAggregatesFilter(BytesFilter, total=False):
    _max: 'BytesFilter'
    _min: 'BytesFilter'
    _sum: 'BytesFilter'
    _avg: 'BytesFilter'
    _count: 'IntFilter'


# TODO: preview feature for improving JSON filtering
JsonFilter = TypedDict(
    'JsonFilter',
    {
        'equals': 'fields.Json',
        'not': 'fields.Json',
    },
    total=False,
)


class JsonWithAggregatesFilter(JsonFilter, total=False):
    _max: 'JsonFilter'
    _min: 'JsonFilter'
    _sum: 'JsonFilter'
    _avg: 'JsonFilter'
    _count: 'IntFilter'


    

DecimalFilter = TypedDict(
    'DecimalFilter',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive1'],
    },
    total=False,
)


DecimalFilterRecursive1 = TypedDict(
    'DecimalFilterRecursive1',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive2'],
    },
    total=False,
)


DecimalFilterRecursive2 = TypedDict(
    'DecimalFilterRecursive2',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive3'],
    },
    total=False,
)


DecimalFilterRecursive3 = TypedDict(
    'DecimalFilterRecursive3',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive4'],
    },
    total=False,
)


DecimalFilterRecursive4 = TypedDict(
    'DecimalFilterRecursive4',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
            },
    total=False,
)


class DecimalWithAggregatesFilter(StringFilter, total=False):
    _max: 'DecimalFilter'
    _min: 'DecimalFilter'
    _sum: 'DecimalFilter'
    _avg: 'DecimalFilter'
    _count: 'IntFilter'


class _FloatSetInput(TypedDict):
    set: float


class _FloatDivideInput(TypedDict):
    divide: float


class _FloatMultiplyInput(TypedDict):
    multiply: float


class _FloatIncrementInput(TypedDict):
    increment: float


class _FloatDecrementInput(TypedDict):
    decrement: float


class _IntSetInput(TypedDict):
    set: int


class _IntDivideInput(TypedDict):
    divide: int


class _IntMultiplyInput(TypedDict):
    multiply: int


class _IntIncrementInput(TypedDict):
    increment: int


class _IntDecrementInput(TypedDict):
    decrement: int


AtomicFloatInput = Union[
    _FloatSetInput,
    _FloatDivideInput,
    _FloatMultiplyInput,
    _FloatIncrementInput,
    _FloatDecrementInput,
]
AtomicIntInput = Union[
    _IntSetInput,
    _IntDivideInput,
    _IntMultiplyInput,
    _IntIncrementInput,
    _IntDecrementInput,
]
AtomicBigIntInput = AtomicIntInput

class _StringListFilterEqualsInput(TypedDict):
    equals: Optional[List[_str]]


class _StringListFilterHasInput(TypedDict):
    has: _str


class _StringListFilterHasEveryInput(TypedDict):
    has_every: List[_str]


class _StringListFilterHasSomeInput(TypedDict):
    has_some: List[_str]


class _StringListFilterIsEmptyInput(TypedDict):
    is_empty: bool


StringListFilter = Union[
    _StringListFilterHasInput,
    _StringListFilterEqualsInput,
    _StringListFilterHasSomeInput,
    _StringListFilterIsEmptyInput,
    _StringListFilterHasEveryInput,
]


class _StringListUpdateSet(TypedDict):
    set: List[_str]


class _StringListUpdatePush(TypedDict):
    push: List[_str]


StringListUpdate = Union[
    List[_str],
    _StringListUpdateSet,
    _StringListUpdatePush,
]

class _BytesListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Base64']]


class _BytesListFilterHasInput(TypedDict):
    has: 'fields.Base64'


class _BytesListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Base64']


class _BytesListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Base64']


class _BytesListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BytesListFilter = Union[
    _BytesListFilterHasInput,
    _BytesListFilterEqualsInput,
    _BytesListFilterHasSomeInput,
    _BytesListFilterIsEmptyInput,
    _BytesListFilterHasEveryInput,
]


class _BytesListUpdateSet(TypedDict):
    set: List['fields.Base64']


class _BytesListUpdatePush(TypedDict):
    push: List['fields.Base64']


BytesListUpdate = Union[
    List['fields.Base64'],
    _BytesListUpdateSet,
    _BytesListUpdatePush,
]

class _DateTimeListFilterEqualsInput(TypedDict):
    equals: Optional[List[datetime.datetime]]


class _DateTimeListFilterHasInput(TypedDict):
    has: datetime.datetime


class _DateTimeListFilterHasEveryInput(TypedDict):
    has_every: List[datetime.datetime]


class _DateTimeListFilterHasSomeInput(TypedDict):
    has_some: List[datetime.datetime]


class _DateTimeListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DateTimeListFilter = Union[
    _DateTimeListFilterHasInput,
    _DateTimeListFilterEqualsInput,
    _DateTimeListFilterHasSomeInput,
    _DateTimeListFilterIsEmptyInput,
    _DateTimeListFilterHasEveryInput,
]


class _DateTimeListUpdateSet(TypedDict):
    set: List[datetime.datetime]


class _DateTimeListUpdatePush(TypedDict):
    push: List[datetime.datetime]


DateTimeListUpdate = Union[
    List[datetime.datetime],
    _DateTimeListUpdateSet,
    _DateTimeListUpdatePush,
]

class _BooleanListFilterEqualsInput(TypedDict):
    equals: Optional[List[_bool]]


class _BooleanListFilterHasInput(TypedDict):
    has: _bool


class _BooleanListFilterHasEveryInput(TypedDict):
    has_every: List[_bool]


class _BooleanListFilterHasSomeInput(TypedDict):
    has_some: List[_bool]


class _BooleanListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BooleanListFilter = Union[
    _BooleanListFilterHasInput,
    _BooleanListFilterEqualsInput,
    _BooleanListFilterHasSomeInput,
    _BooleanListFilterIsEmptyInput,
    _BooleanListFilterHasEveryInput,
]


class _BooleanListUpdateSet(TypedDict):
    set: List[_bool]


class _BooleanListUpdatePush(TypedDict):
    push: List[_bool]


BooleanListUpdate = Union[
    List[_bool],
    _BooleanListUpdateSet,
    _BooleanListUpdatePush,
]

class _IntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _IntListFilterHasInput(TypedDict):
    has: _int


class _IntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _IntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _IntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


IntListFilter = Union[
    _IntListFilterHasInput,
    _IntListFilterEqualsInput,
    _IntListFilterHasSomeInput,
    _IntListFilterIsEmptyInput,
    _IntListFilterHasEveryInput,
]


class _IntListUpdateSet(TypedDict):
    set: List[_int]


class _IntListUpdatePush(TypedDict):
    push: List[_int]


IntListUpdate = Union[
    List[_int],
    _IntListUpdateSet,
    _IntListUpdatePush,
]

class _BigIntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _BigIntListFilterHasInput(TypedDict):
    has: _int


class _BigIntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _BigIntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _BigIntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BigIntListFilter = Union[
    _BigIntListFilterHasInput,
    _BigIntListFilterEqualsInput,
    _BigIntListFilterHasSomeInput,
    _BigIntListFilterIsEmptyInput,
    _BigIntListFilterHasEveryInput,
]


class _BigIntListUpdateSet(TypedDict):
    set: List[_int]


class _BigIntListUpdatePush(TypedDict):
    push: List[_int]


BigIntListUpdate = Union[
    List[_int],
    _BigIntListUpdateSet,
    _BigIntListUpdatePush,
]

class _FloatListFilterEqualsInput(TypedDict):
    equals: Optional[List[_float]]


class _FloatListFilterHasInput(TypedDict):
    has: _float


class _FloatListFilterHasEveryInput(TypedDict):
    has_every: List[_float]


class _FloatListFilterHasSomeInput(TypedDict):
    has_some: List[_float]


class _FloatListFilterIsEmptyInput(TypedDict):
    is_empty: bool


FloatListFilter = Union[
    _FloatListFilterHasInput,
    _FloatListFilterEqualsInput,
    _FloatListFilterHasSomeInput,
    _FloatListFilterIsEmptyInput,
    _FloatListFilterHasEveryInput,
]


class _FloatListUpdateSet(TypedDict):
    set: List[_float]


class _FloatListUpdatePush(TypedDict):
    push: List[_float]


FloatListUpdate = Union[
    List[_float],
    _FloatListUpdateSet,
    _FloatListUpdatePush,
]

class _JsonListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Json']]


class _JsonListFilterHasInput(TypedDict):
    has: 'fields.Json'


class _JsonListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Json']


class _JsonListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Json']


class _JsonListFilterIsEmptyInput(TypedDict):
    is_empty: bool


JsonListFilter = Union[
    _JsonListFilterHasInput,
    _JsonListFilterEqualsInput,
    _JsonListFilterHasSomeInput,
    _JsonListFilterIsEmptyInput,
    _JsonListFilterHasEveryInput,
]


class _JsonListUpdateSet(TypedDict):
    set: List['fields.Json']


class _JsonListUpdatePush(TypedDict):
    push: List['fields.Json']


JsonListUpdate = Union[
    List['fields.Json'],
    _JsonListUpdateSet,
    _JsonListUpdatePush,
]

class _DecimalListFilterEqualsInput(TypedDict):
    equals: Optional[List[decimal.Decimal]]


class _DecimalListFilterHasInput(TypedDict):
    has: decimal.Decimal


class _DecimalListFilterHasEveryInput(TypedDict):
    has_every: List[decimal.Decimal]


class _DecimalListFilterHasSomeInput(TypedDict):
    has_some: List[decimal.Decimal]


class _DecimalListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DecimalListFilter = Union[
    _DecimalListFilterHasInput,
    _DecimalListFilterEqualsInput,
    _DecimalListFilterHasSomeInput,
    _DecimalListFilterIsEmptyInput,
    _DecimalListFilterHasEveryInput,
]


class _DecimalListUpdateSet(TypedDict):
    set: List[decimal.Decimal]


class _DecimalListUpdatePush(TypedDict):
    push: List[decimal.Decimal]


DecimalListUpdate = Union[
    List[decimal.Decimal],
    _DecimalListUpdateSet,
    _DecimalListUpdatePush,
]


# Note types

class NoteOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Note create method"""
    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: _int
    content: _str
    notebook_id: _int
    notebook: 'NotebookCreateNestedWithoutRelationsInput'


class NoteCreateInput(NoteOptionalCreateInput):
    """Required arguments to the Note create method"""
    title: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class NoteOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Note create method, without relations"""
    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: _int
    content: _str
    notebook_id: _int


class NoteCreateWithoutRelationsInput(NoteOptionalCreateWithoutRelationsInput):
    """Required arguments to the Note create method, without relations"""
    title: _str


class NoteCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'NoteCreateWithoutRelationsInput'
    connect: 'NoteWhereUniqueInput'


class NoteCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['NoteCreateWithoutRelationsInput', List['NoteCreateWithoutRelationsInput']]
    connect: Union['NoteWhereUniqueInput', List['NoteWhereUniqueInput']]


_NoteWhereUnique_id_Input = TypedDict(
    '_NoteWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

NoteWhereUniqueInput = _NoteWhereUnique_id_Input


class NoteUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: Union[AtomicIntInput, _int]
    title: _str
    content: _str
    notebook: 'NotebookUpdateOneWithoutRelationsInput'


class NoteUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: Union[AtomicIntInput, _int]
    title: _str
    content: _str


class NoteUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['NoteCreateWithoutRelationsInput']
    connect: List['NoteWhereUniqueInput']
    set: List['NoteWhereUniqueInput']
    disconnect: List['NoteWhereUniqueInput']
    delete: List['NoteWhereUniqueInput']

    # TODO
    # update: List['NoteUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['NoteUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['NoteScalarWhereInput']
    # upsert: List['NoteUpserteWithWhereUniqueWithoutRelationsInput']
    # connectOrCreate: List['NoteCreateOrConnectWithoutRelationsInput']


class NoteUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'NoteCreateWithoutRelationsInput'
    connect: 'NoteWhereUniqueInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'NoteUpdateInput'
    # upsert: 'NoteUpsertWithoutRelationsInput'
    # connectOrCreate: 'NoteCreateOrConnectWithoutRelationsInput'


class NoteUpsertInput(TypedDict):
    create: 'NoteCreateInput'
    update: 'NoteUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Note_created_at_OrderByInput = TypedDict(
    '_Note_created_at_OrderByInput',
    {
        'created_at': 'SortOrder',
    },
    total=True
)

_Note_updated_at_OrderByInput = TypedDict(
    '_Note_updated_at_OrderByInput',
    {
        'updated_at': 'SortOrder',
    },
    total=True
)

_Note_id_OrderByInput = TypedDict(
    '_Note_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Note_title_OrderByInput = TypedDict(
    '_Note_title_OrderByInput',
    {
        'title': 'SortOrder',
    },
    total=True
)

_Note_content_OrderByInput = TypedDict(
    '_Note_content_OrderByInput',
    {
        'content': 'SortOrder',
    },
    total=True
)

_Note_notebook_id_OrderByInput = TypedDict(
    '_Note_notebook_id_OrderByInput',
    {
        'notebook_id': 'SortOrder',
    },
    total=True
)

NoteOrderByInput = Union[
    '_Note_created_at_OrderByInput',
    '_Note_updated_at_OrderByInput',
    '_Note_id_OrderByInput',
    '_Note_title_OrderByInput',
    '_Note_content_OrderByInput',
    '_Note_notebook_id_OrderByInput',
]



# recursive Note types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

NoteRelationFilter = TypedDict(
    'NoteRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class NoteListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class NoteInclude(TypedDict, total=False):
    """Note relational arguments"""
    notebook: Union[bool, 'NotebookArgsFromNote']


    

class NoteIncludeFromNote(TypedDict, total=False):
    """Relational arguments for Note"""
    notebook: Union[bool, 'NotebookArgsFromNoteRecursive1']


class NoteIncludeFromNoteRecursive1(TypedDict, total=False):
    """Relational arguments for Note"""
    notebook: Union[bool, 'NotebookArgsFromNoteRecursive2']


class NoteIncludeFromNoteRecursive2(TypedDict, total=False):
    """Relational arguments for Note"""
    notebook: Union[bool, 'NotebookArgsFromNoteRecursive3']


class NoteIncludeFromNoteRecursive3(TypedDict, total=False):
    """Relational arguments for Note"""
    notebook: Union[bool, 'NotebookArgsFromNoteRecursive4']


class NoteIncludeFromNoteRecursive4(TypedDict, total=False):
    """Relational arguments for Note"""

    

class NoteArgsFromNote(TypedDict, total=False):
    """Arguments for Note"""
    include: 'NoteIncludeFromNoteRecursive1'


class NoteArgsFromNoteRecursive1(TypedDict, total=False):
    """Arguments for Note"""
    include: 'NoteIncludeFromNoteRecursive2'


class NoteArgsFromNoteRecursive2(TypedDict, total=False):
    """Arguments for Note"""
    include: 'NoteIncludeFromNoteRecursive3'


class NoteArgsFromNoteRecursive3(TypedDict, total=False):
    """Arguments for Note"""
    include: 'NoteIncludeFromNoteRecursive4'


class NoteArgsFromNoteRecursive4(TypedDict, total=False):
    """Arguments for Note"""
    
    

class FindManyNoteArgsFromNote(TypedDict, total=False):
    """Arguments for Note"""
    take: int
    skip: int
    order_by: Union['NoteOrderByInput', List['NoteOrderByInput']]
    where: 'NoteWhereInput'
    cursor: 'NoteWhereUniqueInput'
    distinct: List['NoteScalarFieldKeys']
    include: 'NoteIncludeFromNoteRecursive1'


class FindManyNoteArgsFromNoteRecursive1(TypedDict, total=False):
    """Arguments for Note"""
    take: int
    skip: int
    order_by: Union['NoteOrderByInput', List['NoteOrderByInput']]
    where: 'NoteWhereInput'
    cursor: 'NoteWhereUniqueInput'
    distinct: List['NoteScalarFieldKeys']
    include: 'NoteIncludeFromNoteRecursive2'


class FindManyNoteArgsFromNoteRecursive2(TypedDict, total=False):
    """Arguments for Note"""
    take: int
    skip: int
    order_by: Union['NoteOrderByInput', List['NoteOrderByInput']]
    where: 'NoteWhereInput'
    cursor: 'NoteWhereUniqueInput'
    distinct: List['NoteScalarFieldKeys']
    include: 'NoteIncludeFromNoteRecursive3'


class FindManyNoteArgsFromNoteRecursive3(TypedDict, total=False):
    """Arguments for Note"""
    take: int
    skip: int
    order_by: Union['NoteOrderByInput', List['NoteOrderByInput']]
    where: 'NoteWhereInput'
    cursor: 'NoteWhereUniqueInput'
    distinct: List['NoteScalarFieldKeys']
    include: 'NoteIncludeFromNoteRecursive4'


class FindManyNoteArgsFromNoteRecursive4(TypedDict, total=False):
    """Arguments for Note"""
    take: int
    skip: int
    order_by: Union['NoteOrderByInput', List['NoteOrderByInput']]
    where: 'NoteWhereInput'
    cursor: 'NoteWhereUniqueInput'
    distinct: List['NoteScalarFieldKeys']
    
    

class NotebookIncludeFromNote(TypedDict, total=False):
    """Relational arguments for Note"""
    notes: Union[bool, 'FindManyNoteArgsFromNoteRecursive1']


class NotebookIncludeFromNoteRecursive1(TypedDict, total=False):
    """Relational arguments for Note"""
    notes: Union[bool, 'FindManyNoteArgsFromNoteRecursive2']


class NotebookIncludeFromNoteRecursive2(TypedDict, total=False):
    """Relational arguments for Note"""
    notes: Union[bool, 'FindManyNoteArgsFromNoteRecursive3']


class NotebookIncludeFromNoteRecursive3(TypedDict, total=False):
    """Relational arguments for Note"""
    notes: Union[bool, 'FindManyNoteArgsFromNoteRecursive4']


class NotebookIncludeFromNoteRecursive4(TypedDict, total=False):
    """Relational arguments for Note"""

    

class NotebookArgsFromNote(TypedDict, total=False):
    """Arguments for Note"""
    include: 'NotebookIncludeFromNotebookRecursive1'


class NotebookArgsFromNoteRecursive1(TypedDict, total=False):
    """Arguments for Note"""
    include: 'NotebookIncludeFromNotebookRecursive2'


class NotebookArgsFromNoteRecursive2(TypedDict, total=False):
    """Arguments for Note"""
    include: 'NotebookIncludeFromNotebookRecursive3'


class NotebookArgsFromNoteRecursive3(TypedDict, total=False):
    """Arguments for Note"""
    include: 'NotebookIncludeFromNotebookRecursive4'


class NotebookArgsFromNoteRecursive4(TypedDict, total=False):
    """Arguments for Note"""
    
    

class FindManyNotebookArgsFromNote(TypedDict, total=False):
    """Arguments for Note"""
    take: int
    skip: int
    order_by: Union['NotebookOrderByInput', List['NotebookOrderByInput']]
    where: 'NotebookWhereInput'
    cursor: 'NotebookWhereUniqueInput'
    distinct: List['NotebookScalarFieldKeys']
    include: 'NotebookIncludeFromNotebookRecursive1'


class FindManyNotebookArgsFromNoteRecursive1(TypedDict, total=False):
    """Arguments for Note"""
    take: int
    skip: int
    order_by: Union['NotebookOrderByInput', List['NotebookOrderByInput']]
    where: 'NotebookWhereInput'
    cursor: 'NotebookWhereUniqueInput'
    distinct: List['NotebookScalarFieldKeys']
    include: 'NotebookIncludeFromNotebookRecursive2'


class FindManyNotebookArgsFromNoteRecursive2(TypedDict, total=False):
    """Arguments for Note"""
    take: int
    skip: int
    order_by: Union['NotebookOrderByInput', List['NotebookOrderByInput']]
    where: 'NotebookWhereInput'
    cursor: 'NotebookWhereUniqueInput'
    distinct: List['NotebookScalarFieldKeys']
    include: 'NotebookIncludeFromNotebookRecursive3'


class FindManyNotebookArgsFromNoteRecursive3(TypedDict, total=False):
    """Arguments for Note"""
    take: int
    skip: int
    order_by: Union['NotebookOrderByInput', List['NotebookOrderByInput']]
    where: 'NotebookWhereInput'
    cursor: 'NotebookWhereUniqueInput'
    distinct: List['NotebookScalarFieldKeys']
    include: 'NotebookIncludeFromNotebookRecursive4'


class FindManyNotebookArgsFromNoteRecursive4(TypedDict, total=False):
    """Arguments for Note"""
    take: int
    skip: int
    order_by: Union['NotebookOrderByInput', List['NotebookOrderByInput']]
    where: 'NotebookWhereInput'
    cursor: 'NotebookWhereUniqueInput'
    distinct: List['NotebookScalarFieldKeys']
    


FindManyNoteArgs = FindManyNoteArgsFromNote
FindFirstNoteArgs = FindManyNoteArgsFromNote


    

class NoteWhereInput(TypedDict, total=False):
    """Note arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeFilter']
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    content: Union[_str, 'types.StringFilter']
    notebook_id: Union[_int, 'types.IntFilter']
    notebook: 'NotebookRelationFilter'

    # should be noted that AND and NOT should be Union['NoteWhereInputRecursive1', List['NoteWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['NoteWhereInputRecursive1']
    OR: List['NoteWhereInputRecursive1']
    NOT: List['NoteWhereInputRecursive1']


class NoteWhereInputRecursive1(TypedDict, total=False):
    """Note arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeFilter']
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    content: Union[_str, 'types.StringFilter']
    notebook_id: Union[_int, 'types.IntFilter']
    notebook: 'NotebookRelationFilter'

    # should be noted that AND and NOT should be Union['NoteWhereInputRecursive2', List['NoteWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['NoteWhereInputRecursive2']
    OR: List['NoteWhereInputRecursive2']
    NOT: List['NoteWhereInputRecursive2']


class NoteWhereInputRecursive2(TypedDict, total=False):
    """Note arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeFilter']
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    content: Union[_str, 'types.StringFilter']
    notebook_id: Union[_int, 'types.IntFilter']
    notebook: 'NotebookRelationFilter'

    # should be noted that AND and NOT should be Union['NoteWhereInputRecursive3', List['NoteWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['NoteWhereInputRecursive3']
    OR: List['NoteWhereInputRecursive3']
    NOT: List['NoteWhereInputRecursive3']


class NoteWhereInputRecursive3(TypedDict, total=False):
    """Note arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeFilter']
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    content: Union[_str, 'types.StringFilter']
    notebook_id: Union[_int, 'types.IntFilter']
    notebook: 'NotebookRelationFilter'

    # should be noted that AND and NOT should be Union['NoteWhereInputRecursive4', List['NoteWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['NoteWhereInputRecursive4']
    OR: List['NoteWhereInputRecursive4']
    NOT: List['NoteWhereInputRecursive4']


class NoteWhereInputRecursive4(TypedDict, total=False):
    """Note arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeFilter']
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    content: Union[_str, 'types.StringFilter']
    notebook_id: Union[_int, 'types.IntFilter']
    notebook: 'NotebookRelationFilter'



# aggregate Note types


    

class NoteScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Note arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    content: Union[_str, 'types.StringWithAggregatesFilter']
    notebook_id: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['NoteScalarWhereWithAggregatesInputRecursive1']
    OR: List['NoteScalarWhereWithAggregatesInputRecursive1']
    NOT: List['NoteScalarWhereWithAggregatesInputRecursive1']


class NoteScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """Note arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    content: Union[_str, 'types.StringWithAggregatesFilter']
    notebook_id: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['NoteScalarWhereWithAggregatesInputRecursive2']
    OR: List['NoteScalarWhereWithAggregatesInputRecursive2']
    NOT: List['NoteScalarWhereWithAggregatesInputRecursive2']


class NoteScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """Note arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    content: Union[_str, 'types.StringWithAggregatesFilter']
    notebook_id: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['NoteScalarWhereWithAggregatesInputRecursive3']
    OR: List['NoteScalarWhereWithAggregatesInputRecursive3']
    NOT: List['NoteScalarWhereWithAggregatesInputRecursive3']


class NoteScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """Note arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    content: Union[_str, 'types.StringWithAggregatesFilter']
    notebook_id: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['NoteScalarWhereWithAggregatesInputRecursive4']
    OR: List['NoteScalarWhereWithAggregatesInputRecursive4']
    NOT: List['NoteScalarWhereWithAggregatesInputRecursive4']


class NoteScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """Note arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']
    content: Union[_str, 'types.StringWithAggregatesFilter']
    notebook_id: Union[_int, 'types.IntWithAggregatesFilter']



class NoteGroupByOutput(TypedDict, total=False):
    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: _int
    title: _str
    content: _str
    notebook_id: _int
    _sum: 'NoteSumAggregateOutput'
    _avg: 'NoteAvgAggregateOutput'
    _min: 'NoteMinAggregateOutput'
    _max: 'NoteMaxAggregateOutput'
    _count: 'NoteCountAggregateOutput'


class NoteAvgAggregateOutput(TypedDict, total=False):
    """Note output for aggregating averages"""
    id: float
    notebook_id: float


class NoteSumAggregateOutput(TypedDict, total=False):
    """Note output for aggregating sums"""
    id: _int
    notebook_id: _int


class NoteScalarAggregateOutput(TypedDict, total=False):
    """Note output including scalar fields"""
    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: _int
    title: _str
    content: _str
    notebook_id: _int


NoteMinAggregateOutput = NoteScalarAggregateOutput
NoteMaxAggregateOutput = NoteScalarAggregateOutput


class NoteMaxAggregateInput(TypedDict, total=False):
    """Note input for aggregating by max"""
    created_at: bool
    updated_at: bool
    id: bool
    title: bool
    content: bool
    notebook_id: bool


class NoteMinAggregateInput(TypedDict, total=False):
    """Note input for aggregating by min"""
    created_at: bool
    updated_at: bool
    id: bool
    title: bool
    content: bool
    notebook_id: bool


class NoteNumberAggregateInput(TypedDict, total=False):
    """Note input for aggregating numbers"""
    id: bool
    notebook_id: bool


NoteAvgAggregateInput = NoteNumberAggregateInput
NoteSumAggregateInput = NoteNumberAggregateInput


NoteCountAggregateInput = TypedDict(
    'NoteCountAggregateInput',
    {
        'created_at': bool,
        'updated_at': bool,
        'id': bool,
        'title': bool,
        'content': bool,
        'notebook_id': bool,
        '_all': bool,
    },
    total=False,
)

NoteCountAggregateOutput = TypedDict(
    'NoteCountAggregateOutput',
    {
        'created_at': int,
        'updated_at': int,
        'id': int,
        'title': int,
        'content': int,
        'notebook_id': int,
        '_all': int,
    },
    total=False,
)


NoteKeys = Literal[
    'created_at',
    'updated_at',
    'id',
    'title',
    'content',
    'notebook_id',
    'notebook',
]
NoteScalarFieldKeys = Literal[
    'created_at',
    'updated_at',
    'id',
    'title',
    'content',
    'notebook_id',
]
NoteScalarFieldKeysT = TypeVar('NoteScalarFieldKeysT', bound=NoteScalarFieldKeys)

NoteRelationalFieldKeys = Literal[
        'notebook',
    ]

# Notebook types

class NotebookOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Notebook create method"""
    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: _int
    notes: 'NoteCreateManyNestedWithoutRelationsInput'


class NotebookCreateInput(NotebookOptionalCreateInput):
    """Required arguments to the Notebook create method"""
    title: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class NotebookOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Notebook create method, without relations"""
    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: _int


class NotebookCreateWithoutRelationsInput(NotebookOptionalCreateWithoutRelationsInput):
    """Required arguments to the Notebook create method, without relations"""
    title: _str


class NotebookCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'NotebookCreateWithoutRelationsInput'
    connect: 'NotebookWhereUniqueInput'


class NotebookCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['NotebookCreateWithoutRelationsInput', List['NotebookCreateWithoutRelationsInput']]
    connect: Union['NotebookWhereUniqueInput', List['NotebookWhereUniqueInput']]


_NotebookWhereUnique_id_Input = TypedDict(
    '_NotebookWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

NotebookWhereUniqueInput = _NotebookWhereUnique_id_Input


class NotebookUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: Union[AtomicIntInput, _int]
    title: _str
    notes: 'NoteUpdateManyWithoutRelationsInput'


class NotebookUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: Union[AtomicIntInput, _int]
    title: _str


class NotebookUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['NotebookCreateWithoutRelationsInput']
    connect: List['NotebookWhereUniqueInput']
    set: List['NotebookWhereUniqueInput']
    disconnect: List['NotebookWhereUniqueInput']
    delete: List['NotebookWhereUniqueInput']

    # TODO
    # update: List['NotebookUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['NotebookUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['NotebookScalarWhereInput']
    # upsert: List['NotebookUpserteWithWhereUniqueWithoutRelationsInput']
    # connectOrCreate: List['NotebookCreateOrConnectWithoutRelationsInput']


class NotebookUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'NotebookCreateWithoutRelationsInput'
    connect: 'NotebookWhereUniqueInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'NotebookUpdateInput'
    # upsert: 'NotebookUpsertWithoutRelationsInput'
    # connectOrCreate: 'NotebookCreateOrConnectWithoutRelationsInput'


class NotebookUpsertInput(TypedDict):
    create: 'NotebookCreateInput'
    update: 'NotebookUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Notebook_created_at_OrderByInput = TypedDict(
    '_Notebook_created_at_OrderByInput',
    {
        'created_at': 'SortOrder',
    },
    total=True
)

_Notebook_updated_at_OrderByInput = TypedDict(
    '_Notebook_updated_at_OrderByInput',
    {
        'updated_at': 'SortOrder',
    },
    total=True
)

_Notebook_id_OrderByInput = TypedDict(
    '_Notebook_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Notebook_title_OrderByInput = TypedDict(
    '_Notebook_title_OrderByInput',
    {
        'title': 'SortOrder',
    },
    total=True
)

NotebookOrderByInput = Union[
    '_Notebook_created_at_OrderByInput',
    '_Notebook_updated_at_OrderByInput',
    '_Notebook_id_OrderByInput',
    '_Notebook_title_OrderByInput',
]



# recursive Notebook types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

NotebookRelationFilter = TypedDict(
    'NotebookRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class NotebookListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class NotebookInclude(TypedDict, total=False):
    """Notebook relational arguments"""
    notes: Union[bool, 'FindManyNoteArgsFromNotebook']


    

class NoteIncludeFromNotebook(TypedDict, total=False):
    """Relational arguments for Notebook"""
    notebook: Union[bool, 'NotebookArgsFromNotebookRecursive1']


class NoteIncludeFromNotebookRecursive1(TypedDict, total=False):
    """Relational arguments for Notebook"""
    notebook: Union[bool, 'NotebookArgsFromNotebookRecursive2']


class NoteIncludeFromNotebookRecursive2(TypedDict, total=False):
    """Relational arguments for Notebook"""
    notebook: Union[bool, 'NotebookArgsFromNotebookRecursive3']


class NoteIncludeFromNotebookRecursive3(TypedDict, total=False):
    """Relational arguments for Notebook"""
    notebook: Union[bool, 'NotebookArgsFromNotebookRecursive4']


class NoteIncludeFromNotebookRecursive4(TypedDict, total=False):
    """Relational arguments for Notebook"""

    

class NoteArgsFromNotebook(TypedDict, total=False):
    """Arguments for Notebook"""
    include: 'NoteIncludeFromNoteRecursive1'


class NoteArgsFromNotebookRecursive1(TypedDict, total=False):
    """Arguments for Notebook"""
    include: 'NoteIncludeFromNoteRecursive2'


class NoteArgsFromNotebookRecursive2(TypedDict, total=False):
    """Arguments for Notebook"""
    include: 'NoteIncludeFromNoteRecursive3'


class NoteArgsFromNotebookRecursive3(TypedDict, total=False):
    """Arguments for Notebook"""
    include: 'NoteIncludeFromNoteRecursive4'


class NoteArgsFromNotebookRecursive4(TypedDict, total=False):
    """Arguments for Notebook"""
    
    

class FindManyNoteArgsFromNotebook(TypedDict, total=False):
    """Arguments for Notebook"""
    take: int
    skip: int
    order_by: Union['NoteOrderByInput', List['NoteOrderByInput']]
    where: 'NoteWhereInput'
    cursor: 'NoteWhereUniqueInput'
    distinct: List['NoteScalarFieldKeys']
    include: 'NoteIncludeFromNoteRecursive1'


class FindManyNoteArgsFromNotebookRecursive1(TypedDict, total=False):
    """Arguments for Notebook"""
    take: int
    skip: int
    order_by: Union['NoteOrderByInput', List['NoteOrderByInput']]
    where: 'NoteWhereInput'
    cursor: 'NoteWhereUniqueInput'
    distinct: List['NoteScalarFieldKeys']
    include: 'NoteIncludeFromNoteRecursive2'


class FindManyNoteArgsFromNotebookRecursive2(TypedDict, total=False):
    """Arguments for Notebook"""
    take: int
    skip: int
    order_by: Union['NoteOrderByInput', List['NoteOrderByInput']]
    where: 'NoteWhereInput'
    cursor: 'NoteWhereUniqueInput'
    distinct: List['NoteScalarFieldKeys']
    include: 'NoteIncludeFromNoteRecursive3'


class FindManyNoteArgsFromNotebookRecursive3(TypedDict, total=False):
    """Arguments for Notebook"""
    take: int
    skip: int
    order_by: Union['NoteOrderByInput', List['NoteOrderByInput']]
    where: 'NoteWhereInput'
    cursor: 'NoteWhereUniqueInput'
    distinct: List['NoteScalarFieldKeys']
    include: 'NoteIncludeFromNoteRecursive4'


class FindManyNoteArgsFromNotebookRecursive4(TypedDict, total=False):
    """Arguments for Notebook"""
    take: int
    skip: int
    order_by: Union['NoteOrderByInput', List['NoteOrderByInput']]
    where: 'NoteWhereInput'
    cursor: 'NoteWhereUniqueInput'
    distinct: List['NoteScalarFieldKeys']
    
    

class NotebookIncludeFromNotebook(TypedDict, total=False):
    """Relational arguments for Notebook"""
    notes: Union[bool, 'FindManyNoteArgsFromNotebookRecursive1']


class NotebookIncludeFromNotebookRecursive1(TypedDict, total=False):
    """Relational arguments for Notebook"""
    notes: Union[bool, 'FindManyNoteArgsFromNotebookRecursive2']


class NotebookIncludeFromNotebookRecursive2(TypedDict, total=False):
    """Relational arguments for Notebook"""
    notes: Union[bool, 'FindManyNoteArgsFromNotebookRecursive3']


class NotebookIncludeFromNotebookRecursive3(TypedDict, total=False):
    """Relational arguments for Notebook"""
    notes: Union[bool, 'FindManyNoteArgsFromNotebookRecursive4']


class NotebookIncludeFromNotebookRecursive4(TypedDict, total=False):
    """Relational arguments for Notebook"""

    

class NotebookArgsFromNotebook(TypedDict, total=False):
    """Arguments for Notebook"""
    include: 'NotebookIncludeFromNotebookRecursive1'


class NotebookArgsFromNotebookRecursive1(TypedDict, total=False):
    """Arguments for Notebook"""
    include: 'NotebookIncludeFromNotebookRecursive2'


class NotebookArgsFromNotebookRecursive2(TypedDict, total=False):
    """Arguments for Notebook"""
    include: 'NotebookIncludeFromNotebookRecursive3'


class NotebookArgsFromNotebookRecursive3(TypedDict, total=False):
    """Arguments for Notebook"""
    include: 'NotebookIncludeFromNotebookRecursive4'


class NotebookArgsFromNotebookRecursive4(TypedDict, total=False):
    """Arguments for Notebook"""
    
    

class FindManyNotebookArgsFromNotebook(TypedDict, total=False):
    """Arguments for Notebook"""
    take: int
    skip: int
    order_by: Union['NotebookOrderByInput', List['NotebookOrderByInput']]
    where: 'NotebookWhereInput'
    cursor: 'NotebookWhereUniqueInput'
    distinct: List['NotebookScalarFieldKeys']
    include: 'NotebookIncludeFromNotebookRecursive1'


class FindManyNotebookArgsFromNotebookRecursive1(TypedDict, total=False):
    """Arguments for Notebook"""
    take: int
    skip: int
    order_by: Union['NotebookOrderByInput', List['NotebookOrderByInput']]
    where: 'NotebookWhereInput'
    cursor: 'NotebookWhereUniqueInput'
    distinct: List['NotebookScalarFieldKeys']
    include: 'NotebookIncludeFromNotebookRecursive2'


class FindManyNotebookArgsFromNotebookRecursive2(TypedDict, total=False):
    """Arguments for Notebook"""
    take: int
    skip: int
    order_by: Union['NotebookOrderByInput', List['NotebookOrderByInput']]
    where: 'NotebookWhereInput'
    cursor: 'NotebookWhereUniqueInput'
    distinct: List['NotebookScalarFieldKeys']
    include: 'NotebookIncludeFromNotebookRecursive3'


class FindManyNotebookArgsFromNotebookRecursive3(TypedDict, total=False):
    """Arguments for Notebook"""
    take: int
    skip: int
    order_by: Union['NotebookOrderByInput', List['NotebookOrderByInput']]
    where: 'NotebookWhereInput'
    cursor: 'NotebookWhereUniqueInput'
    distinct: List['NotebookScalarFieldKeys']
    include: 'NotebookIncludeFromNotebookRecursive4'


class FindManyNotebookArgsFromNotebookRecursive4(TypedDict, total=False):
    """Arguments for Notebook"""
    take: int
    skip: int
    order_by: Union['NotebookOrderByInput', List['NotebookOrderByInput']]
    where: 'NotebookWhereInput'
    cursor: 'NotebookWhereUniqueInput'
    distinct: List['NotebookScalarFieldKeys']
    


FindManyNotebookArgs = FindManyNotebookArgsFromNotebook
FindFirstNotebookArgs = FindManyNotebookArgsFromNotebook


    

class NotebookWhereInput(TypedDict, total=False):
    """Notebook arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeFilter']
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    notes: 'NoteListRelationFilter'

    # should be noted that AND and NOT should be Union['NotebookWhereInputRecursive1', List['NotebookWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['NotebookWhereInputRecursive1']
    OR: List['NotebookWhereInputRecursive1']
    NOT: List['NotebookWhereInputRecursive1']


class NotebookWhereInputRecursive1(TypedDict, total=False):
    """Notebook arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeFilter']
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    notes: 'NoteListRelationFilter'

    # should be noted that AND and NOT should be Union['NotebookWhereInputRecursive2', List['NotebookWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['NotebookWhereInputRecursive2']
    OR: List['NotebookWhereInputRecursive2']
    NOT: List['NotebookWhereInputRecursive2']


class NotebookWhereInputRecursive2(TypedDict, total=False):
    """Notebook arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeFilter']
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    notes: 'NoteListRelationFilter'

    # should be noted that AND and NOT should be Union['NotebookWhereInputRecursive3', List['NotebookWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['NotebookWhereInputRecursive3']
    OR: List['NotebookWhereInputRecursive3']
    NOT: List['NotebookWhereInputRecursive3']


class NotebookWhereInputRecursive3(TypedDict, total=False):
    """Notebook arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeFilter']
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    notes: 'NoteListRelationFilter'

    # should be noted that AND and NOT should be Union['NotebookWhereInputRecursive4', List['NotebookWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['NotebookWhereInputRecursive4']
    OR: List['NotebookWhereInputRecursive4']
    NOT: List['NotebookWhereInputRecursive4']


class NotebookWhereInputRecursive4(TypedDict, total=False):
    """Notebook arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeFilter']
    id: Union[_int, 'types.IntFilter']
    title: Union[_str, 'types.StringFilter']
    notes: 'NoteListRelationFilter'



# aggregate Notebook types


    

class NotebookScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Notebook arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['NotebookScalarWhereWithAggregatesInputRecursive1']
    OR: List['NotebookScalarWhereWithAggregatesInputRecursive1']
    NOT: List['NotebookScalarWhereWithAggregatesInputRecursive1']


class NotebookScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """Notebook arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['NotebookScalarWhereWithAggregatesInputRecursive2']
    OR: List['NotebookScalarWhereWithAggregatesInputRecursive2']
    NOT: List['NotebookScalarWhereWithAggregatesInputRecursive2']


class NotebookScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """Notebook arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['NotebookScalarWhereWithAggregatesInputRecursive3']
    OR: List['NotebookScalarWhereWithAggregatesInputRecursive3']
    NOT: List['NotebookScalarWhereWithAggregatesInputRecursive3']


class NotebookScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """Notebook arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['NotebookScalarWhereWithAggregatesInputRecursive4']
    OR: List['NotebookScalarWhereWithAggregatesInputRecursive4']
    NOT: List['NotebookScalarWhereWithAggregatesInputRecursive4']


class NotebookScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """Notebook arguments for searching"""
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updated_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    id: Union[_int, 'types.IntWithAggregatesFilter']
    title: Union[_str, 'types.StringWithAggregatesFilter']



class NotebookGroupByOutput(TypedDict, total=False):
    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: _int
    title: _str
    _sum: 'NotebookSumAggregateOutput'
    _avg: 'NotebookAvgAggregateOutput'
    _min: 'NotebookMinAggregateOutput'
    _max: 'NotebookMaxAggregateOutput'
    _count: 'NotebookCountAggregateOutput'


class NotebookAvgAggregateOutput(TypedDict, total=False):
    """Notebook output for aggregating averages"""
    id: float


class NotebookSumAggregateOutput(TypedDict, total=False):
    """Notebook output for aggregating sums"""
    id: _int


class NotebookScalarAggregateOutput(TypedDict, total=False):
    """Notebook output including scalar fields"""
    created_at: datetime.datetime
    updated_at: datetime.datetime
    id: _int
    title: _str


NotebookMinAggregateOutput = NotebookScalarAggregateOutput
NotebookMaxAggregateOutput = NotebookScalarAggregateOutput


class NotebookMaxAggregateInput(TypedDict, total=False):
    """Notebook input for aggregating by max"""
    created_at: bool
    updated_at: bool
    id: bool
    title: bool


class NotebookMinAggregateInput(TypedDict, total=False):
    """Notebook input for aggregating by min"""
    created_at: bool
    updated_at: bool
    id: bool
    title: bool


class NotebookNumberAggregateInput(TypedDict, total=False):
    """Notebook input for aggregating numbers"""
    id: bool


NotebookAvgAggregateInput = NotebookNumberAggregateInput
NotebookSumAggregateInput = NotebookNumberAggregateInput


NotebookCountAggregateInput = TypedDict(
    'NotebookCountAggregateInput',
    {
        'created_at': bool,
        'updated_at': bool,
        'id': bool,
        'title': bool,
        '_all': bool,
    },
    total=False,
)

NotebookCountAggregateOutput = TypedDict(
    'NotebookCountAggregateOutput',
    {
        'created_at': int,
        'updated_at': int,
        'id': int,
        'title': int,
        '_all': int,
    },
    total=False,
)


NotebookKeys = Literal[
    'created_at',
    'updated_at',
    'id',
    'title',
    'notes',
]
NotebookScalarFieldKeys = Literal[
    'created_at',
    'updated_at',
    'id',
    'title',
]
NotebookScalarFieldKeysT = TypeVar('NotebookScalarFieldKeysT', bound=NotebookScalarFieldKeys)

NotebookRelationalFieldKeys = Literal[
        'notes',
    ]



# we have to import ourselves as types can be namespaced to types
from . import types, enums, models, fields